fix: do not break pipeline when seo validation fail

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -60,9 +60,11 @@ jobs:
         run: |
           ACCESS_TOKEN=$ACCESS_TOKEN NEXT_PUBLIC_POSTS_REPO=$NEXT_PUBLIC_POSTS_REPO NEXT_PUBLIC_SITE_ROOT=$NEXT_PUBLIC_SITE_ROOT NEXT_PUBLIC_SITE_TITLE=$NEXT_PUBLIC_SITE_TITLE NEXT_PUBLIC_SITE_DESCRIPTION=$NEXT_PUBLIC_SITE_DESCRIPTION NEXT_PUBLIC_SITE_EMAIL=$NEXT_PUBLIC_SITE_EMAIL NEXT_PUBLIC_SOCIAL_YOUTUBE=$NEXT_PUBLIC_SOCIAL_YOUTUBE NEXT_PUBLIC_SOCIAL_TWITTER=$NEXT_PUBLIC_SOCIAL_TWITTER NEXT_PUBLIC_SOCIAL_LINKEDIN=$NEXT_PUBLIC_SOCIAL_LINKEDIN NEXT_PUBLIC_SOCIAL_GITHUB=$NEXT_PUBLIC_SOCIAL_GITHUB NEXT_PUBLIC_LINK_HOME=$NEXT_PUBLIC_LINK_HOME NEXT_PUBLIC_LINK_ARTICLES=$NEXT_PUBLIC_LINK_ARTICLES NEXT_PUBLIC_LINK_CONTACTS=$NEXT_PUBLIC_LINK_CONTACTS NEXT_PUBLIC_AUTHOR_NAME=$NEXT_PUBLIC_AUTHOR_NAME NEXT_PUBLIC_TWITTER_ACCOUNT=$NEXT_PUBLIC_TWITTER_ACCOUNT npm run build
 
-      - name: Run SEO Validation
+      # run SEO validation without breaking the build
+      - name: SEO Validation
         id: seo-validation
-        run: npm run validate-seo
+        run: |
+          npm run seo-validation || echo "::set-output name=outcome::SEO validation failed. Check the log file for details."
 
       - name: Create Artifact from SEO Validation Results
         if: steps.seo-validation.outcome == 'SEO validation failed. Check the log file for details.'
